### ISSUE TITLE
Document how to find and resolve security vulnerabilities

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-frontend-rtd#22]
We currently have a vuln with node-growl but to me it's unclear which of our dependencies actually depend on it?

Can we document how we resolve these vulnerabilities?

**Comment by megheaiulian** [comment]
@nomego to find vulnerability issues all that is need is a npm 6+ version and it's done automatically. on `npm install` (we get warning). There is a command `npm audit` that lists all found security issues. I will add this in the docs but there isn't much more info.
